name: CI
on:
  pull_request:
  push:
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: olafurpg/setup-scala@v11
      with:
        java-version: zulu@1.11
    - name: Compile
      run: sbt package
    - uses: actions/upload-artifact@v2
      with:
        name: etl.jar
        path: target/scala-2.12/sparketl_2.12-0.1.jar
  upload:
    runs-on: ubuntu-lates
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: python -m  pip install -r req.txt
    - uses: actions/download-artifact@v2
      with:
        name: etl.jar
    - name: Upload file to s3
      run:  python build.py --jar etl.jar --filename etl.jar
  runt_etl:
    runs-on: ubuntu-lates
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: python -m  pip install -r req.txt
    - uses: actions/download-artifact@v2
      with:
        name: etl.jar
    - name: Upload file to s3
      run:  python run_in_emr.py --filename etl.jar
    

